2023-03-27 08:40:01 [ERROR] _callers.py::def _multicall(...)::line 39 > HTTPConnectionPool(host='127.1.1.0', port=1000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002788FCC4F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
