[1m[31mERROR   [0m mylogger:logger.py:83 conftest.py::def setup_teardown(...)::line 52 > HTTPConnectionPool(host='192.168.1.33', port=3002): Max retries exceeded with url: /admin/delete_all_users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D2904EB390>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))